/*
 * SkinDay gallery embed
 * https://skinday.com/gallery-embed.js
 *
 * A clinic's developer installs this once. Every case the clinic publishes then
 * appears on their site automatically, forever, with no further developer
 * involvement. That recurring friction is the thing this replaces.
 *
 *   <script src="https://skinday.com/gallery-embed.js"
 *           data-clinic-id="386"></script>
 *
 * THE DESIGN LIVES HERE, NOT ON THEIR SITE.
 * The host page contains nothing but the script tag. All markup and styling is
 * generated by this file, served from skinday.com. Improve the gallery here and
 * every clinic's gallery improves at once: no redeploys, no version drift, no
 * developer. That is also the point of the subscription.
 *
 * SHADOW DOM.
 * The gallery renders inside a shadow root, so the host site's CSS cannot reach
 * in and our CSS cannot leak out. Clinic sites are unknown WordPress themes with
 * rules like `img { border-radius: 50% }` and `figure { margin: 3rem }` that
 * would otherwise wreck the layout, and there would be nothing we could do from
 * our end. Isolation is what makes one design survive a hundred unknown themes.
 *
 * THEMING (all optional):
 *   data-clinic-id   required
 *   data-columns     desktop columns (default 3)
 *   data-limit       maximum cases shown (default all)
 *   data-accent      accent colour, any CSS colour (default #C9A96E)
 *   data-radius      corner radius in px (default 2)
 *   data-labels      "off" to hide the BEFORE / AFTER tags
 *   data-caption     "off" to hide the treatment line under each case
 *   data-target      id of an existing element to render into
 *
 * Only cases the patient consented to publish are ever returned by the API, so
 * this script cannot display an unconsented case even if it tried.
 */
(function () {
  'use strict';

  var API = 'https://skinday.com/api/clinic-gallery';
  var script = document.currentScript;
  if (!script) return;

  var clinicId = script.getAttribute('data-clinic-id');
  if (!clinicId) {
    console.error('[skinday] gallery embed needs data-clinic-id');
    return;
  }

  var columns = parseInt(script.getAttribute('data-columns'), 10) || 3;
  var limit = parseInt(script.getAttribute('data-limit'), 10) || 0;
  var accent = script.getAttribute('data-accent') || '#C9A96E';
  var radius = script.getAttribute('data-radius');
  radius = (radius === null) ? 2 : (parseInt(radius, 10) || 0);
  var showLabels = script.getAttribute('data-labels') !== 'off';
  var showCaption = script.getAttribute('data-caption') !== 'off';
  var targetId = script.getAttribute('data-target');

  var mount = document.createElement('div');
  mount.className = 'skinday-gallery';
  var target = targetId && document.getElementById(targetId);
  if (target) target.appendChild(mount);
  else script.parentNode.insertBefore(mount, script);

  // Isolated tree. Nothing the host site does can style what is inside it.
  var root = mount.attachShadow ? mount.attachShadow({ mode: 'open' }) : mount;

  var css =
    ':host { display:block; }' +
    '* { box-sizing:border-box; margin:0; padding:0; }' +
    '.grid {' +
      'display:grid;' +
      'grid-template-columns:repeat(' + columns + ',1fr);' +
      'gap:18px;' +
    '}' +
    '@media (max-width:900px){ .grid { grid-template-columns:repeat(2,1fr); } }' +
    '@media (max-width:560px){ .grid { grid-template-columns:1fr; } }' +
    '.case {' +
      'border:1px solid rgba(0,0,0,.10);' +
      'border-radius:' + radius + 'px;' +
      'overflow:hidden;' +
      'background:transparent;' +
    '}' +
    '.pair { display:grid; grid-template-columns:1fr 1fr; gap:1px; background:rgba(0,0,0,.10); }' +
    '.frame { position:relative; overflow:hidden; background:rgba(0,0,0,.03); }' +
    '.frame img {' +
      'display:block; width:100%; height:100%;' +
      'aspect-ratio:4/5; object-fit:cover;' +
      'border-radius:0;' +           // defeat any inherited image rounding
      'filter:none; box-shadow:none;' +
    '}' +
    '.tag {' +
      'position:absolute; left:0; bottom:0;' +
      'background:rgba(20,17,15,.78); color:#fff;' +
      'font:600 9px/1.5 system-ui,sans-serif;' +
      'letter-spacing:.14em; text-transform:uppercase;' +
      'padding:3px 7px;' +
    '}' +
    '.meta {' +
      'padding:10px 12px;' +
      'font:500 12px/1.5 system-ui,sans-serif;' +
      'color:inherit; opacity:.75; text-transform:capitalize;' +
      'border-top:1px solid rgba(0,0,0,.06);' +
    '}' +
    '.meta em { font-style:normal; color:' + accent + '; }' +
    '.foot {' +
      'margin-top:14px;' +
      'font:400 11.5px/1.6 system-ui,sans-serif;' +
      'opacity:.55;' +
    '}' +
    '.empty {' +
      'padding:26px; text-align:center;' +
      'font:400 13px/1.6 system-ui,sans-serif; opacity:.6;' +
      'border:1px dashed rgba(0,0,0,.14); border-radius:' + radius + 'px;' +
    '}';

  var style = document.createElement('style');
  style.textContent = css;
  root.appendChild(style);

  var host = document.createElement('div');
  root.appendChild(host);

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  function figure(url, label) {
    return '<figure class="frame">' +
      '<img loading="lazy" src="' + esc(url) + '" alt="' + label + '">' +
      (showLabels ? '<figcaption class="tag">' + label + '</figcaption>' : '') +
      '</figure>';
  }

  function render(cases) {
    if (!cases.length) {
      host.innerHTML = '<div class="empty">No cases published yet.</div>';
      return;
    }
    var html = '<div class="grid">';
    cases.forEach(function (c) {
      var line = [c.treatment, c.angle].filter(Boolean).join(' &middot; ');
      html +=
        '<div class="case">' +
          '<div class="pair">' + figure(c.before_url, 'Before') + figure(c.after_url, 'After') + '</div>' +
          (showCaption && line ? '<div class="meta">' + esc(c.treatment || '') +
            (c.angle ? ' <em>&middot;</em> ' + esc(c.angle) : '') + '</div>' : '') +
        '</div>';
    });
    html += '</div>';
    html += '<p class="foot">Individual results vary. Published with patient consent.</p>';
    host.innerHTML = html;
  }

  fetch(API + '?clinic_id=' + encodeURIComponent(clinicId))
    .then(function (r) { return r.json(); })
    .then(function (data) {
      if (!data || !data.ok) {
        console.error('[skinday] gallery error', data);
        host.innerHTML = '<div class="empty">Gallery unavailable.</div>';
        return;
      }
      var cases = data.cases || [];
      if (limit > 0) cases = cases.slice(0, limit);
      render(cases);
    })
    .catch(function (err) {
      console.error('[skinday] gallery fetch failed', err);
      host.innerHTML = '<div class="empty">Gallery unavailable.</div>';
    });
})();
