/*
 * SkinDay gallery embed
 * https://skinday.com/gallery-embed.js
 *
 * A clinic's developer installs this once. Every case the clinic publishes then
 * appears on their site automatically, forever, with no further developer
 * involvement. That recurring friction is the thing this replaces.
 *
 *   <script src="https://skinday.com/gallery-embed.js"
 *           data-clinic-id="386"></script>
 *
 * THE DESIGN LIVES HERE, NOT ON THEIR SITE.
 * The host page contains nothing but the script tag. All markup and styling is
 * generated by this file, served from skinday.com. Improve the gallery here and
 * every clinic's gallery improves at once: no redeploys, no version drift, no
 * developer. That is also the point of the subscription.
 *
 * SHADOW DOM.
 * The gallery renders inside a shadow root, so the host site's CSS cannot reach
 * in and our CSS cannot leak out. Clinic sites are unknown WordPress themes with
 * rules like `img { border-radius: 50% }` and `figure { margin: 3rem }` that
 * would otherwise wreck the layout, and there would be nothing we could do from
 * our end. Isolation is what makes one design survive a hundred unknown themes.
 *
 * ---------------------------------------------------------------------------
 * M12: WHY THIS FILE GOT MORE COMPLICATED
 *
 * Two things were wrong, and they were the same thing.
 *
 * CROP. Studio crops to a preset, and only Full Face has a fixed aspect ratio
 * (4:5). Lower Face, Upper Face and Eye Area are derived from facial landmarks,
 * so their shape varies with the patient's jaw width and face height, and Body
 * is the raw photo at whatever the camera gave. Rendering all of that into one
 * 4:5 grid produced a ragged contact sheet, and it was ragged WITHIN a crop, not
 * only across crops. So the gallery now lays out one section per crop, each with
 * an aspect ratio that suits it, and centre-crops to fill. Studio centres the
 * face box, so a centre crop cannot clip the treated area.
 *
 * Most clinics will settle into one or two crops, and a lower-face crop is
 * usually both the treated area and the disclosure the patient actually agreed
 * to, so in practice most galleries are one clean section.
 *
 * SERIES. A 3-timepoint Studio grid saves two cases: before to first follow-up,
 * and before to last. That is correct for Visualize, which grounds on pairs. It
 * was wrong here, where it rendered as two cards sharing a before photo, reading
 * as two patients. The API now also returns a `series` array grouping the cases
 * that came out of one grid, and this file renders a series as one item:
 *
 *   timeline   one patient, tracked. Before, 3 months, 12 months, in a row.
 *   angles     one result, three views. One pair visible, tabs to turn the head.
 *   pair       one before, one after. What it always was.
 *
 * A case saved before M12 has no series id and becomes a series of one, so
 * nothing that already exists stops rendering.
 * ---------------------------------------------------------------------------
 *
 * THEMING (all optional):
 *   data-clinic-id   required
 *   data-columns     desktop columns (default 3, reduced automatically for wide
 *                    crops, ignored for a timeline, which always spans the row)
 *   data-limit       maximum SERIES shown, newest first (default all)
 *   data-accent      accent colour, any CSS colour (default #C9A96E)
 *   data-radius      corner radius in px (default 2)
 *   data-labels      "off" to hide the BEFORE / AFTER / interval tags
 *   data-caption     "off" to hide the treatment and injector lines under each case
 *   data-target      id of an existing element to render into
 *   data-style       "off" to hand the design over entirely (see below)
 *   data-lightbox    "off" to disable click-to-enlarge (on by default in styled
 *                    mode, always off with data-style="off", because that mode
 *                    ships no CSS from us and an unstyled overlay is worse than
 *                    none)
 *   data-cache       "off" to bypass the 10s API cache (for admin previews only;
 *                    a public site should leave the cache alone)
 *
 * WHO OWNS THE DESIGN.
 * By default SkinDay does: shadow DOM, our layout, improved centrally, and the
 * clinic's developer never touches it again.
 *
 * With data-style="off" the clinic owns it: no shadow root, no CSS from us, just
 * semantic markup with stable class names for their own stylesheet to target.
 * The content still updates itself; only the styling becomes theirs.
 *
 *   .skinday-gallery            the container
 *   .skinday-gallery__section   one crop group (data-crop)
 *   .skinday-gallery__grid      wraps the cases in a section
 *   .skinday-gallery__case      one card. Also carries __series, so a stylesheet
 *   .skinday-gallery__series    written before M12 still finds its target.
 *                               (data-mode, data-crop, data-treatment, data-angle)
 *   .skinday-gallery__pair      the before/after pair
 *   .skinday-gallery__strip     a timeline row: before, then each follow-up
 *   .skinday-gallery__figure    one photo (data-when="before" | "after")
 *   .skinday-gallery__img       the image
 *   .skinday-gallery__label     the BEFORE / AFTER / interval caption
 *   .skinday-gallery__tabs      the angle switcher
 *   .skinday-gallery__tab       one angle button (data-angle, aria-selected)
 *   .skinday-gallery__meta      the treatment line
 *   .skinday-gallery__by        the injector line, when the clinic publishes one
 *   .skinday-gallery__note      the results-vary line
 *   .skinday-gallery__empty     shown when nothing is published
 *
 * Only cases the patient consented to publish are ever returned by the API, so
 * this script cannot display an unconsented case even if it tried. And if a
 * patient withdraws consent while a cached response is still in flight, the
 * published image is already gone from storage, so the card removes itself.
 */
(function () {
  'use strict';

  var API = 'https://skinday.com/api/clinic-gallery';
  var script = document.currentScript;
  if (!script) return;

  var clinicId = script.getAttribute('data-clinic-id');
  if (!clinicId) {
    console.error('[skinday] gallery embed needs data-clinic-id');
    return;
  }

  var columns = parseInt(script.getAttribute('data-columns'), 10) || 3;
  var limit = parseInt(script.getAttribute('data-limit'), 10) || 0;
  var accent = script.getAttribute('data-accent') || '#C9A96E';
  var radius = script.getAttribute('data-radius');
  radius = (radius === null) ? 2 : (parseInt(radius, 10) || 0);
  var showLabels = script.getAttribute('data-labels') !== 'off';
  var showCaption = script.getAttribute('data-caption') !== 'off';
  var targetId = script.getAttribute('data-target');
  var noCache = script.getAttribute('data-cache') === 'off';
  // data-style="off" hands the design to the clinic: no shadow root, no CSS from
  // us, just semantic markup their own stylesheet can reach and own.
  var styled = script.getAttribute('data-style') !== 'off';
  // A gallery you cannot look closely at is a gallery that fails at the one thing
  // it is for. On by default. Off in unstyled mode, where we ship no CSS and an
  // unstyled full-screen overlay would be worse than no overlay at all.
  var useLightbox = styled && script.getAttribute('data-lightbox') !== 'off';

  // ---- crop geometry -------------------------------------------------------
  //
  // ratio is the frame each photo is fitted into. cols caps the columns, because
  // a card holds a PAIR side by side, so a card of Eye Area photos at 2:1 each is
  // 4:1 overall and three of those across a page are unreadable stamps.
  //
  // order is the reading order of the sections. Full face first when a clinic has
  // it, because it is the most complete disclosure and the most legible evidence.
  var CROPS = {
    full:  { ratio: '4 / 5', cols: 3, order: 0 },
    lower: { ratio: '4 / 3', cols: 3, order: 1 },
    upper: { ratio: '3 / 2', cols: 2, order: 2 },
    eyes:  { ratio: '2 / 1', cols: 2, order: 3 },
    body:  { ratio: '3 / 4', cols: 3, order: 4 },
    // Cases saved before M12 carry no crop. They were almost all shot full face,
    // and 4:5 is the ratio Studio forces there, so this is the right guess and
    // the only one available.
    unknown: { ratio: '4 / 5', cols: 3, order: 5 }
  };

  var TREATMENT = {
    biostim: 'Biostimulator',
    filler: 'HA filler',
    tox: 'Neurotoxin',
    laser: 'Energy-based'
  };

  var ANGLE = {
    frontal: 'Frontal',
    oblique_right: 'R45', r45: 'R45',
    oblique_left: 'L45', l45: 'L45',
    profile_right: 'R90', r90: 'R90',
    profile_left: 'L90', l90: 'L90'
  };

  var mount = document.createElement('div');
  mount.className = 'skinday-gallery';
  var target = targetId && document.getElementById(targetId);
  if (target) target.appendChild(mount);
  else script.parentNode.insertBefore(mount, script);

  // Styled mode: an isolated tree, so nothing the host site does can reach in and
  // nothing of ours leaks out. Unstyled mode: plain light DOM, because the point
  // is that their CSS *can* reach it.
  var root = (styled && mount.attachShadow)
    ? mount.attachShadow({ mode: 'open' })
    : mount;

  var css =
    ':host { display:block; }' +
    '* { box-sizing:border-box; margin:0; padding:0; }' +
    '.section + .section { margin-top:18px; }' +
    '.grid {' +
      'display:grid;' +
      'grid-template-columns:repeat(var(--cols),1fr);' +
      'gap:18px;' +
      'align-items:start;' +
    '}' +
    '@media (max-width:900px){ .grid { grid-template-columns:repeat(2,1fr); } }' +
    '@media (max-width:560px){ .grid { grid-template-columns:1fr; } }' +
    '.case {' +
      'border:1px solid rgba(0,0,0,.10);' +
      'border-radius:' + radius + 'px;' +
      'overflow:hidden;' +
      'background:transparent;' +
    '}' +
    // A timeline is one patient across time. Cutting it into a column would make
    // it read as separate people, which is the whole thing this is here to stop.
    '.case[data-mode="timeline"] { grid-column:1 / -1; }' +
    '.pair, .strip {' +
      'display:grid; gap:1px; background:rgba(0,0,0,.10);' +
    '}' +
    '.pair { grid-template-columns:1fr 1fr; }' +
    '.strip { grid-template-columns:repeat(var(--steps),1fr); }' +
    '@media (max-width:560px){ .strip { grid-template-columns:1fr 1fr; } }' +
    '.frame { position:relative; overflow:hidden; background:rgba(0,0,0,.03); }' +
    '.frame img {' +
      'display:block; width:100%; height:auto;' +
      'aspect-ratio:var(--ar); object-fit:cover; object-position:center;' +
      'border-radius:0;' +           // defeat any inherited image rounding
      'filter:none; box-shadow:none;' +
    '}' +
    '.tag {' +
      'position:absolute; left:0; bottom:0;' +
      'background:rgba(20,17,15,.78); color:#fff;' +
      'font-size:9px; font-weight:600; line-height:1.5;' +
      'letter-spacing:.14em; text-transform:uppercase;' +
      'padding:3px 7px;' +
    '}' +
    '.tabs {' +
      'display:flex; gap:0;' +
      'border-top:1px solid rgba(0,0,0,.06);' +
    '}' +
    '.tab {' +
      'flex:1; appearance:none; background:none; border:0;' +
      'border-right:1px solid rgba(0,0,0,.06);' +
      'padding:8px 4px; cursor:pointer;' +
      'font:inherit; font-size:10px; font-weight:600;' +
      'letter-spacing:.12em; text-transform:uppercase;' +
      'color:inherit; opacity:.45;' +
    '}' +
    '.tab:last-child { border-right:0; }' +
    '.tab[aria-selected="true"] { opacity:1; color:' + accent + '; }' +
    '.meta {' +
      'padding:10px 12px;' +
      'font-size:12px; font-weight:500; line-height:1.5;' +
      'color:inherit; opacity:.75;' +
      'border-top:1px solid rgba(0,0,0,.06);' +
    '}' +
    '.meta em { font-style:normal; color:' + accent + '; }' +
    '.by {' +
      'padding:0 12px 10px;' +
      'font-size:11px; line-height:1.5;' +
      'color:inherit; opacity:.5;' +
    '}' +
    '.foot {' +
      'margin-top:14px;' +
      'font-size:11.5px; line-height:1.6;' +
      'opacity:.55;' +
    '}' +
    '.empty {' +
      'padding:26px; text-align:center;' +
      'font-size:13px; line-height:1.6; opacity:.6;' +
      'border:1px dashed rgba(0,0,0,.14); border-radius:' + radius + 'px;' +
    '}' +
    // Click to enlarge. The card crops to a common frame so the grid stays even;
    // the lightbox does the opposite, showing the whole photograph uncropped,
    // because at that point the visitor is studying a face and not scanning a page.
    (useLightbox ? '.frame img { cursor:zoom-in; }' : '') +
    '.lb {' +
      'position:fixed; inset:0; z-index:2147483000;' +
      'background:rgba(20,17,15,.94);' +
      'display:none; align-items:center; justify-content:center;' +
      'padding:32px 24px;' +
    '}' +
    '.lb.open { display:flex; }' +
    '.lb-inner { width:100%; max-width:1180px; max-height:100%; overflow:auto; }' +
    '.lb .pair { display:flex; justify-content:center; align-items:center; gap:0; background:transparent; }' +
    '.lb .strip { background:transparent; gap:10px; }' +
    '.lb .frame { background:transparent; overflow:visible; }' +
    // frame hugs its image (not a fixed half-column), so portrait and landscape
    // pairs both sit edge to edge with no gap in the middle.
    '.lb .pair .frame { display:flex; flex:0 0 auto; width:auto; max-width:none; }' +
    '.lb .frame img { aspect-ratio:auto; object-fit:contain; width:100%; height:auto; max-height:76vh; }' +
    '.lb .pair .frame img { width:auto; height:auto; max-width:48vw; max-height:82vh; }' +
    '@media (max-width:560px){ .lb .pair { flex-direction:column; } .lb .pair .frame img { max-width:92vw; max-height:40vh; } }' +
    '.lb .meta {' +
      'border-top:0; padding:14px 0 0; text-align:center;' +
      'color:#e8e0d6; opacity:.8; font-size:13px;' +
    '}' +
    '.lb .by {' +
      'padding:4px 0 0; text-align:center;' +
      'color:#e8e0d6; opacity:.5; font-size:12px;' +
    '}' +
    '.lb-nav {' +
      'position:fixed; top:50%; transform:translateY(-50%); z-index:5;' +
      'background:rgba(255,255,255,.12); color:#fff; border:0; cursor:pointer;' +
      'width:52px; height:52px; border-radius:50%; font-size:30px; line-height:1;' +
      'align-items:center; justify-content:center;' +
    '}' +
    '.lb-nav:hover { background:rgba(255,255,255,.22); }' +
    '.lb.open .lb-nav.show { display:flex; }' +
    '.lb-nav { display:none; }' +
    '.lb-prev { left:20px; }' +
    '.lb-next { right:20px; }' +
    '.lb-angle {' +
      'position:fixed; bottom:22px; left:0; right:0; text-align:center;' +
      'color:#e8e0d6; font-size:12px; letter-spacing:.14em; text-transform:uppercase;' +
    '}' +
    '.lb-close {' +
      'position:absolute; top:14px; right:18px;' +
      'appearance:none; background:none; border:0;' +
      'color:#e8e0d6; font-size:30px; line-height:1;' +
      'cursor:pointer; padding:6px 10px; opacity:.7;' +
    '}' +
    '.lb-close:hover { opacity:1; }';

  if (styled) {
    var style = document.createElement('style');
    style.textContent = css;
    root.appendChild(style);
  }

  var host = document.createElement('div');
  root.appendChild(host);

  // ---- lightbox ------------------------------------------------------------
  //
  // Clicking a photograph opens the whole GROUP it belongs to, not the single
  // image: the before/after pair, or the full timeline strip. A before photo on
  // its own is not evidence of anything, and a visitor who clicks an after photo
  // wants to compare it to something, not admire it alone.
  //
  // The group is cloned out of the live card, so whichever angle tab is currently
  // selected is the one that enlarges. Uncropped: the card frames to a common
  // aspect ratio to keep the grid even, and the lightbox undoes exactly that.
  var lb = null;
  var lbInner = null;

  if (useLightbox) {
    lb = document.createElement('div');
    lb.className = 'lb';
    lb.setAttribute('role', 'dialog');
    lb.setAttribute('aria-modal', 'true');

    var lbClose = document.createElement('button');
    lbClose.className = 'lb-close';
    lbClose.type = 'button';
    lbClose.setAttribute('aria-label', 'Close');
    lbClose.innerHTML = '&times;';

    lbInner = document.createElement('div');
    lbInner.className = 'lb-inner';

    var lbPrev = document.createElement('button');
    lbPrev.className = 'lb-nav lb-prev'; lbPrev.type = 'button';
    lbPrev.setAttribute('aria-label', 'Previous angle'); lbPrev.innerHTML = '\u2039';
    var lbNext = document.createElement('button');
    lbNext.className = 'lb-nav lb-next'; lbNext.type = 'button';
    lbNext.setAttribute('aria-label', 'Next angle'); lbNext.innerHTML = '\u203A';
    var lbAngle = document.createElement('div');
    lbAngle.className = 'lb-angle';

    lb.appendChild(lbClose);
    lb.appendChild(lbPrev);
    lb.appendChild(lbNext);
    lb.appendChild(lbAngle);
    lb.appendChild(lbInner);
    root.appendChild(lb);

    lbClose.addEventListener('click', closeLightbox);
    lbPrev.addEventListener('click', function (e) { e.stopPropagation(); stepLb(-1); });
    lbNext.addEventListener('click', function (e) { e.stopPropagation(); stepLb(1); });
    lb.addEventListener('click', function (e) {
      // Backdrop only. A click on a photograph should not close the thing the
      // visitor opened in order to look at the photograph.
      if (e.target === lb) closeLightbox();
    });
    document.addEventListener('keydown', function (e) {
      if (!lb.classList.contains('open')) return;
      if (e.key === 'Escape' || e.key === 'Esc') closeLightbox();
      else if (e.key === 'ArrowLeft') stepLb(-1);
      else if (e.key === 'ArrowRight') stepLb(1);
    });
  }

  // The lightbox arrows move between the ANGLES OF ONE CASE only -- never across
  // to a different patient. slides is rebuilt for whichever card was opened.
  var slides = [];
  var lbIdx = 0;

  function slidesForCard(cardEl) {
    var out = [];
    var tabs = cardEl.querySelectorAll('[role="tab"]');
    if (tabs.length) {
      Array.prototype.forEach.call(tabs, function (tab) {
        out.push({ cardEl: cardEl, tab: tab });
      });
    } else {
      out.push({ cardEl: cardEl, tab: null });
    }
    return out;
  }

  function renderSlide(i) {
    if (i < 0 || i >= slides.length) return;
    lbIdx = i;
    var sl = slides[i];
    lbInner.innerHTML = '';
    if (sl.tab) {
      // Build the pair from the angle tab's stored urls (styled mode only, so the
      // 'pair'/'frame' class names are the styled ones).
      var pair = document.createElement('div');
      pair.className = 'pair';
      pair.innerHTML =
        '<figure class="frame"><img alt=""><figcaption>Before</figcaption></figure>' +
        '<figure class="frame"><img alt=""><figcaption>After</figcaption></figure>';
      var pImgs = pair.querySelectorAll('img');
      pImgs[0].src = sl.tab.getAttribute('data-before') || '';
      pImgs[1].src = sl.tab.getAttribute('data-after') || '';
      lbInner.appendChild(pair);
    } else {
      var group = sl.cardEl.querySelector('.pair, .strip');
      if (group) lbInner.appendChild(group.cloneNode(true));
    }
    var meta = sl.cardEl.querySelector('.meta');
    if (meta) lbInner.appendChild(meta.cloneNode(true));
    var by = sl.cardEl.querySelector('.by');
    if (by) lbInner.appendChild(by.cloneNode(true));
    if (lbAngle) lbAngle.textContent = sl.tab ? (sl.tab.textContent || '') : '';
    var multi = slides.length > 1;
    lbPrev.className = 'lb-nav lb-prev' + (multi ? ' show' : '');
    lbNext.className = 'lb-nav lb-next' + (multi ? ' show' : '');
  }

  function stepLb(dir) {
    if (slides.length < 2) return;
    renderSlide((lbIdx + dir + slides.length) % slides.length);
  }

  function openLightbox(cardEl) {
    if (!lb || !cardEl) return;
    // Only this case's angles. Single-angle cases get one slide (no arrows).
    slides = slidesForCard(cardEl);
    var selectedTab = cardEl.querySelector('[role="tab"][aria-selected="true"]');
    var startIdx = 0;
    for (var i = 0; i < slides.length; i++) {
      if (!slides[i].tab || slides[i].tab === selectedTab) { startIdx = i; break; }
    }
    renderSlide(startIdx);
    lb.classList.add('open');
    // The host page keeps scrolling behind a fixed overlay otherwise, which reads
    // as the page being broken rather than as an overlay being open.
    document.documentElement.style.overflow = 'hidden';
  }

  function closeLightbox() {
    if (!lb) return;
    lb.classList.remove('open');
    lbInner.innerHTML = '';
    document.documentElement.style.overflow = '';
  }

  function wireLightbox() {
    if (!useLightbox) return;
    host.querySelectorAll('img').forEach(function (img) {
      img.addEventListener('click', function () {
        openLightbox(img.closest('[data-series]'));
      });
    });
  }

  // Class names differ by mode: short and private inside the shadow root, but
  // long, stable and documented in the light DOM, because in that mode they are
  // a public contract with the clinic's developer.
  var C = styled
    ? { section:'section', grid:'grid', case:'case', series:'case',
        pair:'pair', strip:'strip', figure:'frame', img:'', label:'tag',
        tabs:'tabs', tab:'tab', meta:'meta', by:'by', note:'foot', empty:'empty' }
    : { section:'skinday-gallery__section', grid:'skinday-gallery__grid',
        case:'skinday-gallery__case', series:'skinday-gallery__series',
        pair:'skinday-gallery__pair', strip:'skinday-gallery__strip',
        figure:'skinday-gallery__figure', img:'skinday-gallery__img',
        label:'skinday-gallery__label', tabs:'skinday-gallery__tabs',
        tab:'skinday-gallery__tab', meta:'skinday-gallery__meta',
        by:'skinday-gallery__by',
        note:'skinday-gallery__note', empty:'skinday-gallery__empty' };

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // "6 months" is the honest resolution of the underlying data: a clinic often
  // knows the month a treatment happened but not the day, so Studio never asked
  // for one and this never pretends to have one.
  function intervalLabel(n) {
    if (n === null || n === undefined || !isFinite(n) || n <= 0) return 'After';
    if (n === 1) return '1 month';
    if (n < 12) return n + ' months';
    if (n === 12) return '1 year';
    if (n % 12 === 0) return (n / 12) + ' years';
    return n + ' months';
  }

  function figure(url, label, when) {
    return '<figure class="' + C.figure + '" data-when="' + when + '">' +
      '<img class="' + C.img + '" loading="lazy" src="' + esc(url) + '" alt="' + esc(label) + '">' +
      (showLabels
        ? '<figcaption class="' + C.label + '">' + esc(label) + '</figcaption>'
        : '') +
      '</figure>';
  }

  // A before/after with no dates is a claim. With them it is evidence.
  //
  // The caption is the CLINIC's words, not ours. TREATMENT is SkinDay's taxonomy,
  // which is the right vocabulary for matching a generation to a reference and the
  // wrong one to print under a face: a visitor wants to know what was done to this
  // patient, and only the clinic can say that. So the treatment label from Studio
  // wins, and the category name is only a fallback for cases saved before the label
  // was carried, or where the clinic left the field blank.
  function metaLine(s) {
    var first = s.cases[0] || {};
    var name = first.treatment_label ||
               s.treatment_label ||
               TREATMENT[s.treatment] || s.treatment || '';
    var span = (first.before_date && first.after_date)
      ? first.before_date + ' \u2192 ' + (s.cases[s.cases.length - 1].after_date || first.after_date)
      : (first.before_date || first.after_date || '');
    return [name, span].filter(Boolean).join(' \u00b7 ');
  }

  // Who did it, when the clinic chose to say so.
  //
  // Its own line, not appended to the treatment. "Sculptra 6 vials, Dr Andy Huang,
  // Nov 2024 to Feb 2025" reads as one run-on fact. The injector is attribution,
  // which is a different kind of statement from what was done and when, and it is
  // the one a named person has a stake in. It gets its own line and a quieter one.
  //
  // Null means the clinic did not choose to publish a name. That is not the same
  // as there not being one, and nothing here should imply otherwise.
  function byLine(s) {
    var name = (s.cases[0] && s.cases[0].injector_name) || s.injector_name;
    if (!name) return '';
    return '<div class="' + C.by + '">' + esc(name) + '</div>';
  }

  // Timeline: one before, then every follow-up that was published, in order.
  // The before is shared by every case in the series (they came from one grid and
  // one photograph), so it is drawn once and the row reads as a progression
  // rather than as a set of unrelated pairs.
  function timelineBody(s) {
    var first = s.cases[0];
    var html = '<div class="' + C.strip + '" style="--steps:' + (s.cases.length + 1) + ';">';
    html += figure(first.before_url, 'Before', 'before');
    s.cases.forEach(function (c) {
      html += figure(c.after_url, intervalLabel(c.interval_months), 'after');
    });
    html += '</div>';
    return html;
  }

  // Angles: six photos in a card is a wall. Show one pair and let the visitor
  // turn the head, which is also how the clinician looked at the result.
  function anglesBody(s) {
    var first = s.cases[0];
    var html =
      '<div class="' + C.pair + '">' +
        figure(first.before_url, 'Before', 'before') +
        figure(first.after_url, 'After', 'after') +
      '</div>' +
      '<div class="' + C.tabs + '" role="tablist">';
    s.cases.forEach(function (c, i) {
      html +=
        '<button class="' + C.tab + '" type="button" role="tab"' +
        ' data-angle="' + esc(c.angle || '') + '"' +
        ' data-before="' + esc(c.before_url) + '"' +
        ' data-after="' + esc(c.after_url) + '"' +
        ' aria-selected="' + (i === 0 ? 'true' : 'false') + '">' +
        esc(ANGLE[c.angle] || c.angle || 'View') +
        '</button>';
    });
    html += '</div>';
    return html;
  }

  function pairBody(s) {
    var c = s.cases[0];
    return '<div class="' + C.pair + '">' +
      figure(c.before_url, 'Before', 'before') +
      figure(c.after_url, intervalLabel(c.interval_months), 'after') +
      '</div>';
  }

  function card(s) {
    var body =
      s.mode === 'timeline' ? timelineBody(s) :
      s.mode === 'angles'   ? anglesBody(s) :
                              pairBody(s);
    var line = metaLine(s);
    return '<div class="' + C.case + ' ' + C.series + '"' +
      ' data-mode="' + esc(s.mode) + '"' +
      ' data-crop="' + esc(s.crop || 'unknown') + '"' +
      ' data-treatment="' + esc(s.treatment || '') + '"' +
      ' data-angle="' + esc(s.angle || '') + '"' +
      ' data-series="' + esc(s.series_id) + '">' +
      body +
      (showCaption && line ? '<div class="' + C.meta + '">' + esc(line) + '</div>' : '') +
      (showCaption ? byLine(s) : '') +
      '</div>';
  }

  function empty() {
    host.innerHTML = '<div class="' + C.empty + '">No cases published yet.</div>';
  }

  function render(series) {
    if (!series.length) { empty(); return; }

    // Group by crop, in a fixed reading order, so like sits with like and every
    // row in a section is the same shape. A clinic that only ever shoots lower
    // face sees one clean section and never knows this code exists.
    var groups = {};
    series.forEach(function (s) {
      var key = (s.crop && CROPS[s.crop]) ? s.crop : 'unknown';
      (groups[key] = groups[key] || []).push(s);
    });

    var keys = Object.keys(groups).sort(function (a, b) {
      return CROPS[a].order - CROPS[b].order;
    });

    var html = '';
    keys.forEach(function (key) {
      var cfg = CROPS[key];
      var cols = Math.min(columns, cfg.cols);
      html +=
        '<div class="' + C.section + '" data-skinday-section data-crop="' + key + '"' +
        ' style="--ar:' + cfg.ratio + ';">' +
          '<div class="' + C.grid + '" style="--cols:' + cols + ';">' +
            groups[key].map(card).join('') +
          '</div>' +
        '</div>';
    });
    html += '<p class="' + C.note + '">Individual results vary. Published with patient consent.</p>';
    host.innerHTML = html;

    wireTabs();
    wireImageFailure();
    wireLightbox();
  }

  function wireTabs() {
    host.querySelectorAll('[role="tab"]').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var cardEl = btn.parentNode.parentNode;
        var imgs = cardEl.querySelectorAll('img');
        if (imgs.length < 2) return;
        imgs[0].src = btn.getAttribute('data-before');
        imgs[1].src = btn.getAttribute('data-after');
        cardEl.setAttribute('data-angle', btn.getAttribute('data-angle'));
        btn.parentNode.querySelectorAll('[role="tab"]').forEach(function (b) {
          b.setAttribute('aria-selected', b === btn ? 'true' : 'false');
        });
      });
    });
  }

  // The API response is cached briefly. If a patient withdraws consent
  // inside that window the JSON can still name a case, but its published object
  // is already deleted, so the image 404s. Remove the whole card rather than leave
  // a broken frame on a clinic's website: a card that cannot load its photographs
  // is not evidence of anything.
  //
  // Prune by [data-skinday-section], NOT by [data-crop]. Both the section and the
  // card carry data-crop, and querySelector does not match the element it is
  // called on, so a card, which IS the [data-series] element, reads as empty and
  // deletes itself. One dead image would have taken the entire gallery with it.
  function wireImageFailure() {
    host.querySelectorAll('img').forEach(function (img) {
      img.addEventListener('error', function () {
        var cardEl = img.closest('[data-series]');
        if (cardEl) cardEl.remove();
        host.querySelectorAll('[data-skinday-section]').forEach(function (sec) {
          if (!sec.querySelector('[data-series]')) sec.remove();
        });
        if (!host.querySelector('[data-series]')) empty();
      });
    });
  }

  // Older responses, and any consumer that built against the flat contract, still
  // work: a case with no series is a series of one.
  function seriesFrom(data) {
    if (Array.isArray(data.series) && data.series.length) return data.series;
    return (data.cases || []).map(function (c) {
      return {
        series_id: c.case_id,
        mode: 'pair',
        treatment: c.treatment,
        subtype: c.subtype,
        crop: c.crop || null,
        angle: c.angle,
        interval_months: c.interval_months === undefined ? null : c.interval_months,
        created_at: c.created_at,
        cases: [c]
      };
    });
  }

  var url = API + '?clinic_id=' + encodeURIComponent(clinicId);
  if (noCache) url += '&_=' + Date.now();

  fetch(url, noCache ? { cache: 'no-store' } : undefined)
    .then(function (r) { return r.json(); })
    .then(function (data) {
      if (!data || !data.ok) {
        console.error('[skinday] gallery error', data);
        host.innerHTML = '<div class="' + C.empty + '">Gallery unavailable.</div>';
        return;
      }
      var series = seriesFrom(data);
      if (limit > 0) series = series.slice(0, limit);
      render(series);
    })
    .catch(function (err) {
      console.error('[skinday] gallery fetch failed', err);
      host.innerHTML = '<div class="' + C.empty + '">Gallery unavailable.</div>';
    });
})();
