/*
 * SkinDay gallery embed
 * https://skinday.com/gallery-embed.js
 *
 * A clinic's developer installs this once. Every case the clinic publishes then
 * appears on their site automatically, forever, with no further developer
 * involvement. That recurring friction is the thing this replaces.
 *
 *   <script src="https://skinday.com/gallery-embed.js"
 *           data-clinic-id="386"></script>
 *
 * THE DESIGN LIVES HERE, NOT ON THEIR SITE.
 * The host page contains nothing but the script tag. All markup and styling is
 * generated by this file, served from skinday.com. Improve the gallery here and
 * every clinic's gallery improves at once: no redeploys, no version drift, no
 * developer. That is also the point of the subscription.
 *
 * SHADOW DOM.
 * The gallery renders inside a shadow root, so the host site's CSS cannot reach
 * in and our CSS cannot leak out. Clinic sites are unknown WordPress themes with
 * rules like `img { border-radius: 50% }` and `figure { margin: 3rem }` that
 * would otherwise wreck the layout, and there would be nothing we could do from
 * our end. Isolation is what makes one design survive a hundred unknown themes.
 *
 * THEMING (all optional):
 *   data-clinic-id   required
 *   data-columns     desktop columns (default 3)
 *   data-limit       maximum cases shown (default all)
 *   data-accent      accent colour, any CSS colour (default #C9A96E)
 *   data-radius      corner radius in px (default 2)
 *   data-labels      "off" to hide the BEFORE / AFTER tags
 *   data-caption     "off" to hide the treatment line under each case
 *   data-target      id of an existing element to render into
 *   data-style       "off" to hand the design over entirely (see below)
 *
 * WHO OWNS THE DESIGN.
 * By default SkinDay does: shadow DOM, our layout, improved centrally, and the
 * clinic's developer never touches it again.
 *
 * With data-style="off" the clinic owns it: no shadow root, no CSS from us, just
 * semantic markup with stable class names for their own stylesheet to target.
 * The content still updates itself; only the styling becomes theirs.
 *
 *   .skinday-gallery            the container
 *   .skinday-gallery__grid      wraps all cases
 *   .skinday-gallery__case      one case
 *   .skinday-gallery__pair      the before/after pair
 *   .skinday-gallery__figure    one photo (data-when="before" | "after")
 *   .skinday-gallery__img       the image
 *   .skinday-gallery__label     the BEFORE / AFTER caption
 *   .skinday-gallery__meta      the treatment line
 *   .skinday-gallery__note      the results-vary line
 *   .skinday-gallery__empty     shown when nothing is published
 *
 * Only cases the patient consented to publish are ever returned by the API, so
 * this script cannot display an unconsented case even if it tried.
 */
(function () {
  'use strict';

  var API = 'https://skinday.com/api/clinic-gallery';
  var script = document.currentScript;
  if (!script) return;

  var clinicId = script.getAttribute('data-clinic-id');
  if (!clinicId) {
    console.error('[skinday] gallery embed needs data-clinic-id');
    return;
  }

  var columns = parseInt(script.getAttribute('data-columns'), 10) || 3;
  var limit = parseInt(script.getAttribute('data-limit'), 10) || 0;
  var accent = script.getAttribute('data-accent') || '#C9A96E';
  var radius = script.getAttribute('data-radius');
  radius = (radius === null) ? 2 : (parseInt(radius, 10) || 0);
  var showLabels = script.getAttribute('data-labels') !== 'off';
  var showCaption = script.getAttribute('data-caption') !== 'off';
  var targetId = script.getAttribute('data-target');
  // data-style="off" hands the design to the clinic: no shadow root, no CSS from
  // us, just semantic markup their own stylesheet can reach and own.
  var styled = script.getAttribute('data-style') !== 'off';

  var mount = document.createElement('div');
  mount.className = 'skinday-gallery';
  var target = targetId && document.getElementById(targetId);
  if (target) target.appendChild(mount);
  else script.parentNode.insertBefore(mount, script);

  // Styled mode: an isolated tree, so nothing the host site does can reach in and
  // nothing of ours leaks out. Unstyled mode: plain light DOM, because the point
  // is that their CSS *can* reach it.
  var root = (styled && mount.attachShadow)
    ? mount.attachShadow({ mode: 'open' })
    : mount;

  var css =
    ':host { display:block; }' +
    '* { box-sizing:border-box; margin:0; padding:0; }' +
    '.grid {' +
      'display:grid;' +
      'grid-template-columns:repeat(' + columns + ',1fr);' +
      'gap:18px;' +
    '}' +
    '@media (max-width:900px){ .grid { grid-template-columns:repeat(2,1fr); } }' +
    '@media (max-width:560px){ .grid { grid-template-columns:1fr; } }' +
    '.case {' +
      'border:1px solid rgba(0,0,0,.10);' +
      'border-radius:' + radius + 'px;' +
      'overflow:hidden;' +
      'background:transparent;' +
    '}' +
    '.pair { display:grid; grid-template-columns:1fr 1fr; gap:1px; background:rgba(0,0,0,.10); }' +
    '.frame { position:relative; overflow:hidden; background:rgba(0,0,0,.03); }' +
    '.frame img {' +
      'display:block; width:100%; height:100%;' +
      'aspect-ratio:4/5; object-fit:cover;' +
      'border-radius:0;' +           // defeat any inherited image rounding
      'filter:none; box-shadow:none;' +
    '}' +
    '.tag {' +
      'position:absolute; left:0; bottom:0;' +
      'background:rgba(20,17,15,.78); color:#fff;' +
      'font-size:9px; font-weight:600; line-height:1.5;' +
      'letter-spacing:.14em; text-transform:uppercase;' +
      'padding:3px 7px;' +
    '}' +
    '.meta {' +
      'padding:10px 12px;' +
      'font-size:12px; font-weight:500; line-height:1.5;' +
      'color:inherit; opacity:.75; text-transform:capitalize;' +
      'border-top:1px solid rgba(0,0,0,.06);' +
    '}' +
    '.meta em { font-style:normal; color:' + accent + '; }' +
    '.foot {' +
      'margin-top:14px;' +
      'font-size:11.5px; line-height:1.6;' +
      'opacity:.55;' +
    '}' +
    '.empty {' +
      'padding:26px; text-align:center;' +
      'font-size:13px; line-height:1.6; opacity:.6;' +
      'border:1px dashed rgba(0,0,0,.14); border-radius:' + radius + 'px;' +
    '}';

  if (styled) {
    var style = document.createElement('style');
    style.textContent = css;
    root.appendChild(style);
  }

  var host = document.createElement('div');
  root.appendChild(host);

  // Class names differ by mode: short and private inside the shadow root, but
  // long, stable and documented in the light DOM, because in that mode they are
  // a public contract with the clinic's developer.
  var C = styled
    ? { grid:'grid', case:'case', pair:'pair', figure:'frame', img:'', label:'tag',
        meta:'meta', note:'foot', empty:'empty' }
    : { grid:'skinday-gallery__grid', case:'skinday-gallery__case',
        pair:'skinday-gallery__pair', figure:'skinday-gallery__figure',
        img:'skinday-gallery__img', label:'skinday-gallery__label',
        meta:'skinday-gallery__meta', note:'skinday-gallery__note',
        empty:'skinday-gallery__empty' };

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  function figure(url, label) {
    var when = label.toLowerCase();
    return '<figure class="' + C.figure + '" data-when="' + when + '">' +
      '<img class="' + C.img + '" loading="lazy" src="' + esc(url) + '" alt="' + label + '">' +
      (showLabels ? '<figcaption class="' + C.label + '">' + label + '</figcaption>' : '') +
      '</figure>';
  }

  function render(cases) {
    if (!cases.length) {
      host.innerHTML = '<div class="' + C.empty + '">No cases published yet.</div>';
      return;
    }
    var html = '<div class="' + C.grid + '">';
    cases.forEach(function (c) {
      var line = [c.treatment, c.angle].filter(Boolean).join(' \u00b7 ');
      html +=
        '<div class="' + C.case + '" data-treatment="' + esc(c.treatment || '') +
          '" data-angle="' + esc(c.angle || '') + '">' +
          '<div class="' + C.pair + '">' +
            figure(c.before_url, 'Before') + figure(c.after_url, 'After') +
          '</div>' +
          (showCaption && line
            ? '<div class="' + C.meta + '">' + esc(line) + '</div>'
            : '') +
        '</div>';
    });
    html += '</div>';
    html += '<p class="' + C.note + '">Individual results vary. Published with patient consent.</p>';
    host.innerHTML = html;
  }

  fetch(API + '?clinic_id=' + encodeURIComponent(clinicId))
    .then(function (r) { return r.json(); })
    .then(function (data) {
      if (!data || !data.ok) {
        console.error('[skinday] gallery error', data);
        host.innerHTML = '<div class="empty">Gallery unavailable.</div>';
        return;
      }
      var cases = data.cases || [];
      if (limit > 0) cases = cases.slice(0, limit);
      render(cases);
    })
    .catch(function (err) {
      console.error('[skinday] gallery fetch failed', err);
      host.innerHTML = '<div class="empty">Gallery unavailable.</div>';
    });
})();
